### ISSUE TITLE
sys-fs/sanoid/files/sanoid.cron cron entry

### ISSUE THREAD

**Issue by ste7677** [thehaven/haven-overlay#3]
Hi thehaven,

is it absolutely necessary to force UTC on the cron job? For me, snapshots were taken with the **wrong timestamp**

On my setup,

`* * * * * root /usr/bin/sanoid --cron`

instead of 

`* * * * * root TZ=UTC /usr/bin/sanoid --cron`

worked.

I don' want to fork your entire overly for that change. If you agree, please modify and PR right back to sanoid.

Thank you for the package :-) !

**Comment by thehaven** [comment]
Sure, I'll remove that and PR it.

**Comment by thehaven** [comment]
https://github.com/thehaven/haven-overlay/commit/656be3633e547f05d262eb3d503d47b6b1752add for the local change.

**Comment by thehaven** [comment]
https://github.com/jimsalterjrs/sanoid/pull/369 pull request raised. Closing this down. Holler if there are any other issues.

**Comment by thehaven** [comment]
656be36 reverted as upstream do not want to implement. If you really need this then forking is going to be the best way forward.
